"""
PDF report export helpers.

Uses reportlab to create a compact industrial-style incident report PDF
from the existing report dicts generated by the plant service.
"""

from __future__ import annotations

from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle


def _paragraph_style(name: str, base, **kwargs):
    return ParagraphStyle(name, parent=base, **kwargs)


def build_report_pdf(report: dict[str, Any]) -> BytesIO:
    buffer = BytesIO()
    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=16 * mm,
        leftMargin=16 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
    )

    styles = getSampleStyleSheet()
    styles.add(_paragraph_style("TitleDark", styles["Title"], fontName="Helvetica-Bold", fontSize=20, leading=24, textColor=colors.HexColor("#0f172a"), alignment=TA_LEFT))
    styles.add(_paragraph_style("SectionDark", styles["Heading2"], fontName="Helvetica-Bold", fontSize=12.5, leading=16, textColor=colors.HexColor("#0f172a")))
    styles.add(_paragraph_style("BodyDark", styles["BodyText"], fontName="Helvetica", fontSize=9.5, leading=13, textColor=colors.HexColor("#1f2937")))

    sensor = report.get("sensor_readings", {})
    actions = report.get("corrective_actions", [])

    story = [
        Paragraph("Virtual Plant Operator Incident Report", styles["TitleDark"]),
        Spacer(1, 6),
        Paragraph(f"Report ID: <b>{report.get('report_id', 'N/A')}</b>", styles["BodyDark"]),
        Paragraph(f"Timestamp: <b>{report.get('timestamp', 'N/A')}</b>", styles["BodyDark"]),
        Paragraph(f"Severity: <b>{report.get('severity', 'N/A')}</b>", styles["BodyDark"]),
        Paragraph(f"Anomaly Type: <b>{report.get('anomaly_type', 'N/A')}</b>", styles["BodyDark"]),
        Spacer(1, 10),
        Paragraph("Sensor Readings", styles["SectionDark"]),
    ]

    sensor_table = Table(
        [["Temperature", f"{sensor.get('temperature', 'N/A')} °C"],
         ["Pressure", f"{sensor.get('pressure', 'N/A')} bar"],
         ["Flow Rate", f"{sensor.get('flow_rate', 'N/A')} L/min"],
         ["Vibration", f"{sensor.get('vibration', 'N/A')} g"]],
        colWidths=[45 * mm, 65 * mm],
    )
    sensor_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#dbeafe")),
        ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#f8fafc")),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#0f172a")),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))

    story.extend([sensor_table, Spacer(1, 10), Paragraph("Corrective Actions", styles["SectionDark"])])

    if actions:
        for action in actions:
            story.append(Paragraph(f"• <b>{action.get('priority', 'N/A')}</b> - {action.get('action', 'N/A')}", styles["BodyDark"]))
    else:
        story.append(Paragraph("No corrective actions recorded.", styles["BodyDark"]))

    story.extend([
        Spacer(1, 10),
        Paragraph("AI Analysis", styles["SectionDark"]),
        Paragraph(report.get("ai_analysis", "No AI analysis available."), styles["BodyDark"]),
        Spacer(1, 10),
        Paragraph("Health Summary", styles["SectionDark"]),
        Paragraph(f"Score: <b>{report.get('health_score', 'N/A')}</b> | Grade: <b>{report.get('health_grade', 'N/A')}</b>", styles["BodyDark"]),
    ])

    document.build(story)
    buffer.seek(0)
    return buffer


generate_pdf_response = build_report_pdf

